server:
  port: 8007
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&ZQYY%f3q2 # 登录校验的密钥
    pubKeyPath: D:\IdeaProject\leyou\ly-auth-center\ly-auth-common\bystander\rsa.pub # 公钥地址
    priKeyPath: D:\IdeaProject\leyou\ly-auth-center\ly-auth-common\bystander\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN