server:
  port: 8006
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=GMT%2B8
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.80.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.80.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: com.leyou.user.pojo
ly:
  user:
    exchange: ly.sms.exchange
    routingKey: sms.verify.code
    timeOut: 5