server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**  #商品微服务
    search-service: /search/** #搜索微服务
    auth-service: /auth/** #授权中心微服务
    cart-service: /cart/** #购物车微服务
    order-service: /order/** #订单微服务
    user-service:
      path: /user/** #用户中心微服务
      serviceId: user-service
      strip-prefix: false
    upload-service:
      path: /upload/** #文件上传微服务
      serviceId: upload-service
      strip-prefix: false #不忽略路径upload，即在路径/upload被解析为服务id后，其仍然在路径上，即解析完后不是/upload-service，而是/upload-service/upload
  add-host-header: true #添加host头信息
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长5000ms
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 30000 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
ly:
  jwt:
    pubKeyPath: D:\IdeaProject\leyou\ly-auth-center\ly-auth-common\bystander\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/send
      - /api/item